name: Go Run

on:
  push:
    paths:
    - '**.go'

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Run modified files
      run: |
        mod_files=$(git diff HEAD HEAD~1 --name-only|grep .go)